### ISSUE TITLE
Verify readiness for multiple repository IDs

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/FixCache#2]
We may need to run this on a database where there are multiple repositories inside. These are identified by the repository ID. Can you verify that your code will work correctly with multiple repositories?

For example, it looks like findNumberOfBugs() doesn't respect the repository ID, and searches on date and is_bug_fix. This will match commits that aren't part of the same repository, so will fail.

**Comment by xyzhu** [comment]
I think this has been fixed.

**Comment by supertri** [comment]
Actually, we may not need repository ids after all in, for example, findNumberOfBugs (although there are some other places we needed them). It looks like file id's are the primary key for the files table, and so counting the number of previous bug fixes in a file does not need to join on repository id.
