### ISSUE TITLE
Testing needs to be independent of a database

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/FixCache#25]
I'm working on getting FixCache in our Continuous Integration engine http://eisbox.soe.ucsc.edu/jenkins.

However, the necessity of having a database running before you can test FixCache is a bit difficult. You shouldn't need to admin/access a DB to test.

Instead, the tests could/should use SQLite, so it stores the DB in memory/in a file. There appears to be a good description of using SQLite with Java here:

http://stackoverflow.com/questions/41233/java-and-sqlite

**Comment by supertri** [comment]
Xiaoyan did this.
