### ISSUE TITLE
Reduce Findbugs warnings

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/FixCache#30]
Now that everything is in Maven (yay!), we can do some more cool reporting. Jenkins is now running CheckStyle and Findbugs. CheckStyle is something we can leave for now (and is currently reporting 1400+ errors, so that's a bit too much ;) ), but Findbugs is reporting a more reasonable ~40, and Findbugs is pretty good at highlighting possible failure modes.

Please look at the builds on Jenkins to see the Findbugs reports (like [this one](http://eisbox.soe.ucsc.edu/jenkins/job/FixCache/7/findbugsResult/)) and try getting that count down. This can happen after MSR camera-ready, but would be good for ensuring _deployable code_.

**Comment by supertri** [comment]
Ok. I changed everything I am planning to change from all Findbugs reports. I made two issues for widespread changes that could be made. 

There are unfortunately false positive null pointer errors whenever System.out.println() or System.err.println() are used.

**Comment by cflewis** [comment]
Did you push your change? Jenkins is saying only 3 were fixed.

**Comment by supertri** [comment]
Perhaps Jenkins should be running our dev branch.

Also, note that there will be unfixed:

16 "NP_ALWAYS_NULL" caused by printing to System.out or System.err
12 "OBL_UNSATISFIED_OBLIGATION" for database error handling. See GH 32.
4 "SE_COMPARATOR_SHOULD_BE_SERIALIZABLE" 

plus a couple others.
