### ISSUE TITLE
Code review notes

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/FixCache#6]
I can't comment inline on files, only commits, so here are my comments:
1. Change your settings so files are 4 spaces, not 8 or the tabs there are now.
2. Some files, like CacheItem.java is well over 78 columns, please fix. Usually it's SQL statements that go over. Split these up into multiple lines, usually splitting like

select [stuff]

from [tables]

where [conditions]
1. Formatting on `Simulator.java` is a bit dodgy, see the try/catch starting at line 148. 
2. What is Simulator doing? I notice that it ignores anything but .java files. This is not something that should happen with the live repos, there are source files of all different types. The FileTypes table will tell you whether a file is source code or not, and you should match against that. The Content extension only adds stuff to the Content table if it is either a code file or an "unknown"file. If the file can't be converted to UTF-8, it's thrown out. This means "unknown"s that weren't text of some description are ignored.
3. DBOperation has a method called `ExeQuery`, this should be named `execQuery` to follow convention (lowercase 'e' and use of word 'exec')
4. DBOperation has a password in it. _Really?!_ If this file isn't used, delete it from the repo using `git rm DBOperation.java` (it'll stay in history). Otherwise please get this password out.
5. Dodgy curly brace formatting throughout `DatabaseManager.java`, particularly the catch on line 91, and indentation on everything in the `main()`.
6. Not anything I see wrong, but how are you handling dates when you get them out of the database? Does JDBC get you a native date automatically, or do you have to give it a format string?
7. You don't appear to have a `.gitignore` file. You should create one and use it to make sure you never accidentally check in password files, built class files etc. etc. If you have a good `.gitignore`, you can just do `git add .` and add everything to every commit, as all things that shouldn't be added are ignored.

That's it I think. I wasn't checking code correctness, just formatting and cleanliness. I did note you've moved to prepared statements and using the repository ID, which is great. 

Looking through the code essentially blind reminds me that we all need to do some hard commenting and documentation after the paper :)

**Comment by supertri** [comment]
Joda-Time is the standard time library, so I opened a new issue about converting to that:
https://github.com/supertri/FixCache/issues#issue/7

Regarding the 78 character limit: in my experience, this is not standard for Java due to verboseness. I usually use a 160 character limit. Conservative limits in prominent open source projects (e.g. https://sites.google.com/a/android.com/opensource/submit-patches/code-style-guide#linelen) are 100 characters.

**Comment by cflewis** [comment]
80 characters is favored by the official docs:

http://java.sun.com/docs/codeconv/html/CodeConventions.doc3.html

160 characters is far too long for GitHub reading, and is twice as long as the standard 80, and is a full 60 characters bigger than your cited limit. Please cut line length down.

**Comment by supertri** [comment]
Yes, we have converted to 100 characters (e.g. Android developer code style) as the specification.
