### ISSUE TITLE
Pay attentions to warning of Java compiler

### ISSUE THREAD

**Issue by linzhp** [SoftwareIntrospectionLab/FixCache#8]
I found a lot of warning in fixcache code. Although the code may still work with those warnings, it is not good to live with them.

The most frequent warnings in fixcache is using Java raw type instead of generic. I would recommend try to use generic in most cases.

Other warnings can be solved by clicking the little yellow exclamation point left to the code if you are using Eclipse.

**Comment by supertri** [comment]
These warnings were in trusted third-party library code. Not worth cleaning right now; added a SupressWarnings annotation so warnings no longer appear.

**Comment by linzhp** [comment]
All the warning I referred to are in FixCache/src, I don't believe they are third-party code. If they are, please put them in other directory, src/ dir is only for our code.
